### ISSUE TITLE
cache build fails on "unexpanded" machine

### ISSUE THREAD

**Issue by sanchon** [kounch/knloader#3]
In my unexpanded zx spectrum next I get an error whenever I try to build the cache file.

Apparently I cannot use bank 48. This line:
`6070 LET %k=13:BANK 48 ERASE 0:LET %j=0:;Current Bank, Current Base Address`
fails with "Out of Memory"

I guess that the right thing to do would be to check the MAXBNK System Variable...

**Comment by kounch** [comment]
You are right. A miscalculation on my part. Bank numbers start at 0, so it should, at least, be 47 instead of 48, but i will check also your suggestion

**Comment by kounch** [comment]
Since everything is cleared after building, i have changed it to BANKS 13 and 14 (faster than using a variable), and this should work on everything, including a ZX-Uno with the Next Core. 

Can you try the attached `knloader.bas` and report back here if it works ok for you?

[knloader.bas.zip](https://github.com/kounch/knloader/files/4955962/knloader.bas.zip)

**Comment by kounch** [comment]
Included in 1.0 RC3

**Comment by sanchon** [comment]
Now it works ok! Thanks!!!
